arch: 
    - ppc64le
    - amd64
language: go

go:
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - tip

jobs:
 exclude:
 exclude:
  - go: 1.0
    arch: ppc64le
  - go: 1.1
    arch: ppc64le
  - go: 1.2
    arch: ppc64le
  - go: 1.3
    arch: ppc64le

script:
    - go test

matrix:
    allow_failures:
        - go: tip
